/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posproject;

import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Calendar;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class POSFrame extends javax.swing.JFrame {

    ArrayList<Barang> daftarBarang;
    ArrayList<Makanan> daftarMakanan;
    ArrayList<Pulsa> daftarPulsa;
    ArrayList<Token> daftarToken;
    TableModel daftarModel;
    int totalBarang;
    int totalBelanja;
    int pilihan = 0;
    QRIS invoiceQRIS = null;

    /**
     * Creates new form POSFrame
     */
    public POSFrame() {

        DBConnector.InitDBConnection();

        Makanan.loadMakananFromDB();
        Pulsa.loadPulsaFromDB();
        Token.loadTokenFromDB();
        daftarPulsa = Pulsa.daftarPulsa;
        daftarMakanan = Makanan.daftarMakanan;
        daftarToken = Token.daftarToken;
        System.out.println(daftarMakanan.size());
        System.out.println(daftarPulsa.size());
        System.out.println(daftarToken.size());
        initComponents();

        daftarModel = daftarTable.getModel();
        daftarModel.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {

                if (e.getColumn() == 4) {
                    var baris = e.getFirstRow();

                    var harga = (float) daftarModel.getValueAt(baris, 3);
                    var jumlah = (int) daftarModel.getValueAt(baris, 4);

                    var total = harga * jumlah;
                    daftarModel.setValueAt(total, baris, 5);

                    totalBelanja = 0;

                    for (int i = 0; i < totalBarang; i++) {
                        total = (float) daftarModel.getValueAt(i, 5);
                        totalBelanja += total;
                    }

                    totalBelanjaTextField.setText(String.format("%,d", totalBelanja));
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dialogPembayaranKas = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        nominalKasTextField = new javax.swing.JTextField();
        konfirmasiKasButton = new javax.swing.JButton();
        batalKasButton = new javax.swing.JButton();
        dialogPembayaranKartuDebit = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        bankTextField = new javax.swing.JTextField();
        konfirmasiKartuDebitButton = new javax.swing.JButton();
        batalKartuDebitButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        nomorKartuTextField = new javax.swing.JTextField();
        dialogPembayaranQRIS = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        kontenTextField = new javax.swing.JTextField();
        konfirmasiQRISButton = new javax.swing.JButton();
        batalQRISButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        requestDateTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        invoiceIDTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kodeTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        ketTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarTable = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        totalBelanjaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        togglePulsa = new javax.swing.JToggleButton();
        togglePLN = new javax.swing.JToggleButton();
        toggleFood = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        comboBoxMetodePembayaran = new javax.swing.JComboBox<>();
        transaksiButton = new javax.swing.JButton();

        dialogPembayaranKas.setTitle("Transaksi Kas");
        dialogPembayaranKas.setModal(true);
        dialogPembayaranKas.setResizable(false);
        dialogPembayaranKas.setSize(new java.awt.Dimension(0, 0));

        jLabel5.setText("Nominal");

        konfirmasiKasButton.setText("Konfirmasi");
        konfirmasiKasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiKasButtonActionPerformed(evt);
            }
        });

        batalKasButton.setText("Batal");
        batalKasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalKasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogPembayaranKasLayout = new javax.swing.GroupLayout(dialogPembayaranKas.getContentPane());
        dialogPembayaranKas.getContentPane().setLayout(dialogPembayaranKasLayout);
        dialogPembayaranKasLayout.setHorizontalGroup(
            dialogPembayaranKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPembayaranKasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPembayaranKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPembayaranKasLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nominalKasTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPembayaranKasLayout.createSequentialGroup()
                        .addGap(0, 104, Short.MAX_VALUE)
                        .addComponent(batalKasButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(konfirmasiKasButton)))
                .addContainerGap())
        );
        dialogPembayaranKasLayout.setVerticalGroup(
            dialogPembayaranKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPembayaranKasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPembayaranKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nominalKasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPembayaranKasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalKasButton)
                    .addComponent(konfirmasiKasButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogPembayaranKartuDebit.setTitle("Transaksi QRIS");
        dialogPembayaranKartuDebit.setModal(true);

        jLabel9.setText("Bank");

        konfirmasiKartuDebitButton.setText("Konfirmasi");
        konfirmasiKartuDebitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiKartuDebitButtonActionPerformed(evt);
            }
        });

        batalKartuDebitButton.setText("Batal");
        batalKartuDebitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalKartuDebitButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Nomor Kartu");

        javax.swing.GroupLayout dialogPembayaranKartuDebitLayout = new javax.swing.GroupLayout(dialogPembayaranKartuDebit.getContentPane());
        dialogPembayaranKartuDebit.getContentPane().setLayout(dialogPembayaranKartuDebitLayout);
        dialogPembayaranKartuDebitLayout.setHorizontalGroup(
            dialogPembayaranKartuDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPembayaranKartuDebitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPembayaranKartuDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPembayaranKartuDebitLayout.createSequentialGroup()
                        .addGap(0, 104, Short.MAX_VALUE)
                        .addComponent(batalKartuDebitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(konfirmasiKartuDebitButton))
                    .addGroup(dialogPembayaranKartuDebitLayout.createSequentialGroup()
                        .addGroup(dialogPembayaranKartuDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogPembayaranKartuDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankTextField)
                            .addComponent(nomorKartuTextField))))
                .addContainerGap())
        );
        dialogPembayaranKartuDebitLayout.setVerticalGroup(
            dialogPembayaranKartuDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPembayaranKartuDebitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPembayaranKartuDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bankTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPembayaranKartuDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nomorKartuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPembayaranKartuDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalKartuDebitButton)
                    .addComponent(konfirmasiKartuDebitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogPembayaranQRIS.setTitle("Transaksi Kartu Debit");
        dialogPembayaranQRIS.setModal(true);

        jLabel6.setText("Konten");

        kontenTextField.setEditable(false);

        konfirmasiQRISButton.setText("Scan");
        konfirmasiQRISButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiQRISButtonActionPerformed(evt);
            }
        });

        batalQRISButton.setText("Batal");
        batalQRISButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalQRISButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Request Date");

        requestDateTextField.setEditable(false);

        jLabel11.setText("Invoice ID");

        invoiceIDTextField.setEditable(false);

        javax.swing.GroupLayout dialogPembayaranQRISLayout = new javax.swing.GroupLayout(dialogPembayaranQRIS.getContentPane());
        dialogPembayaranQRIS.getContentPane().setLayout(dialogPembayaranQRISLayout);
        dialogPembayaranQRISLayout.setHorizontalGroup(
            dialogPembayaranQRISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPembayaranQRISLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPembayaranQRISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogPembayaranQRISLayout.createSequentialGroup()
                        .addGap(0, 119, Short.MAX_VALUE)
                        .addComponent(batalQRISButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(konfirmasiQRISButton))
                    .addGroup(dialogPembayaranQRISLayout.createSequentialGroup()
                        .addGroup(dialogPembayaranQRISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogPembayaranQRISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kontenTextField)
                            .addComponent(requestDateTextField)
                            .addComponent(invoiceIDTextField))))
                .addContainerGap())
        );
        dialogPembayaranQRISLayout.setVerticalGroup(
            dialogPembayaranQRISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPembayaranQRISLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogPembayaranQRISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kontenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPembayaranQRISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(requestDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPembayaranQRISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(invoiceIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogPembayaranQRISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batalQRISButton)
                    .addComponent(konfirmasiQRISButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode");

        jLabel2.setText("Nama");

        jLabel3.setText("Harga");

        kodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeTextFieldActionPerformed(evt);
            }
        });
        kodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kodeTextFieldKeyReleased(evt);
            }
        });

        namaTextField.setEditable(false);

        ketTextField.setEditable(false);
        ketTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketTextFieldActionPerformed(evt);
            }
        });

        daftarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Nama", "Harga Satuan", "Jumlah", "Total", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        daftarTable.setShowGrid(true);
        jScrollPane1.setViewportView(daftarTable);
        if (daftarTable.getColumnModel().getColumnCount() > 0) {
            daftarTable.getColumnModel().getColumn(0).setResizable(false);
            daftarTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            daftarTable.getColumnModel().getColumn(1).setResizable(false);
            daftarTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            daftarTable.getColumnModel().getColumn(2).setResizable(false);
            daftarTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            daftarTable.getColumnModel().getColumn(3).setResizable(false);
            daftarTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            daftarTable.getColumnModel().getColumn(4).setResizable(false);
            daftarTable.getColumnModel().getColumn(4).setPreferredWidth(20);
            daftarTable.getColumnModel().getColumn(5).setResizable(false);
            daftarTable.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        totalBelanjaTextField.setEditable(false);
        totalBelanjaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBelanjaTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Total Belanja");

        buttonGroup1.add(togglePulsa);
        togglePulsa.setText("PULSA");
        togglePulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePulsaActionPerformed(evt);
            }
        });

        buttonGroup1.add(togglePLN);
        togglePLN.setText("PLN");
        togglePLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePLNActionPerformed(evt);
            }
        });

        buttonGroup1.add(toggleFood);
        toggleFood.setText("Food");
        toggleFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleFoodActionPerformed(evt);
            }
        });

        jLabel7.setText("Metode Pembayaran");

        comboBoxMetodePembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kas", "Kartu Debit", "QRIS" }));

        transaksiButton.setText("Lakukan Transaksi");
        transaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toggleFood, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(togglePLN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(togglePulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(transaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBelanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(kodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(togglePulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(togglePLN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(toggleFood, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBelanjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(transaksiButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeTextFieldActionPerformed
        var kodeInput = kodeTextField.getText();
        if (pilihan == 0) {
            var makanan = Makanan.getMakanan(kodeInput);
            if (makanan != null) {
                var kadaluarsa = makanan.getKadaluarsa();
                kadaluarsa = kadaluarsa.plus(1, ChronoUnit.WEEKS);
                for (int i = 0; i < totalBarang; i++) {
                    var kode = daftarModel.getValueAt(i, 1);
                    if (kode.equals(kodeInput)) {
                        JOptionPane.showMessageDialog(this, "Barang sudah di input, harap edit kolom jumlah.");
                        return;
                    }
                }

                // WARNING: tempIndex digunakan untuk indexing baris dimulai dari index 0
                int tempIndex = totalBarang;

                totalBarang++;

                System.out.println("Barang ditemukan");
                namaTextField.setText(makanan.nama);
                ketTextField.setText(Float.toString(makanan.harga));

                daftarModel.setValueAt(totalBarang, tempIndex, 0);
                daftarModel.setValueAt(kodeInput, tempIndex, 1);
                daftarModel.setValueAt(makanan.nama, tempIndex, 2);
                daftarModel.setValueAt(makanan.harga, tempIndex, 3);
                daftarModel.setValueAt(1, tempIndex, 4);
                daftarModel.setValueAt(makanan.harga, tempIndex, 5);
                daftarModel.setValueAt(kadaluarsa, tempIndex, 6);

            }
            if (makanan == null) {
                JOptionPane.showMessageDialog(this, "Kode yang anda tidak terdaftar di database.");
            }

        }
        if (pilihan == 1) {
            var token = Token.getToken(kodeInput);
            if (token != null) {
                System.out.println("Barang ditemukan");
                namaTextField.setText(token.nama);
                ketTextField.setEditable(true);
            }
            if (token == null) {
                JOptionPane.showMessageDialog(this, "Kode yang anda tidak terdaftar di database.");
            }
        }
        if (pilihan == 2) {
            var pulsa = Pulsa.getPulsa(kodeInput);
            if (pulsa != null) {
                System.out.println("Barang ditemukan");
                namaTextField.setText(pulsa.getOperator() + " " + pulsa.getNominal());
                ketTextField.setEditable(true);
            }
            if (pulsa == null) {
                JOptionPane.showMessageDialog(this, "Kode yang anda tidak terdaftar di database.");
            }
        }

    }//GEN-LAST:event_kodeTextFieldActionPerformed

    private void kodeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kodeTextFieldKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_kodeTextFieldKeyReleased

    private void ketTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketTextFieldActionPerformed
        // TODO add your handling code here:
        if (pilihan == 1) {
            var meteran = ketTextField.getText();
            var kodeInput = kodeTextField.getText();
            var token = Token.getToken(kodeInput);
            token.setNoMeteran(meteran);
            float hargaToken = token.getNominal() + 2000;
            long noToken = (long) (Math.random() * 1000000000000000L);
            token.setToken(noToken);
            int tempIndex = totalBarang;
            totalBarang++;
            daftarModel.setValueAt(totalBarang, tempIndex, 0);
            daftarModel.setValueAt(kodeInput, tempIndex, 1);
            daftarModel.setValueAt(token.nama, tempIndex, 2);
            daftarModel.setValueAt(hargaToken, tempIndex, 3);
            daftarModel.setValueAt(1, tempIndex, 4);
            daftarModel.setValueAt(hargaToken, tempIndex, 5);
            daftarModel.setValueAt(token.getToken(), tempIndex, 6);
        }
        if (pilihan == 2) {
            var NoHP = ketTextField.getText();
            var kodeInput = kodeTextField.getText();
            var pulsa = Pulsa.getPulsa(kodeInput);
            pulsa.setNoTelp(NoHP);
            float hargaPulsa = pulsa.getNominal() + 2000;
            int tempIndex = totalBarang;
            totalBarang++;
            daftarModel.setValueAt(totalBarang, tempIndex, 0);
            daftarModel.setValueAt(kodeInput, tempIndex, 1);
            daftarModel.setValueAt(pulsa.getOperator() + " " + pulsa.getNominal(), tempIndex, 2);
            daftarModel.setValueAt(hargaPulsa, tempIndex, 3);
            daftarModel.setValueAt(1, tempIndex, 4);
            daftarModel.setValueAt(hargaPulsa, tempIndex, 5);
            daftarModel.setValueAt(pulsa.getNoTelp(), tempIndex, 6);
        }
    }//GEN-LAST:event_ketTextFieldActionPerformed

    private void totalBelanjaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBelanjaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBelanjaTextFieldActionPerformed

    private void toggleFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleFoodActionPerformed
        // TODO add your handling code here:
        if (toggleFood.isSelected()) {
            pilihan = 0;
            jLabel3.setText("Harga");
            ketTextField.setEditable(false);
        }
    }//GEN-LAST:event_toggleFoodActionPerformed

    private void togglePLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePLNActionPerformed
        // TODO add your handling code here:
        if (togglePLN.isSelected()) {
            pilihan = 1;
            jLabel3.setText("Meteran");
        }

    }//GEN-LAST:event_togglePLNActionPerformed

    private void togglePulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePulsaActionPerformed
        // TODO add your handling code here:
        if (togglePulsa.isSelected()) {
            pilihan = 2;
            jLabel3.setText("No.Hp");

        }

    }//GEN-LAST:event_togglePulsaActionPerformed

    private void transaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiButtonActionPerformed
        var metodeTransaksiId = comboBoxMetodePembayaran.getSelectedIndex();
        
        JDialog dialogPembayaran = null;
        
        switch (metodeTransaksiId) {
            case 0:
                dialogPembayaran = dialogPembayaranKas;
                break;
            case 1:
                dialogPembayaran = dialogPembayaranKartuDebit;
                break;
            case 2:
                dialogPembayaran = dialogPembayaranQRIS;
                invoiceQRIS = new QRIS(LocalDateTime.now());
                invoiceQRIS.setIDPembayaran(getLatestTransactionId() + 1);
                invoiceQRIS.setTotalHarga(totalBelanja);
                invoiceQRIS.setWaktuPembayaran(LocalDateTime.now());
                kontenTextField.setText(invoiceQRIS.getKonten());
                requestDateTextField.setText(invoiceQRIS.getRequestDate().toString());
                invoiceIDTextField.setText(invoiceQRIS.getInvoiceID());
                break;
        }
        
        if (dialogPembayaran == null) {
            JOptionPane.showMessageDialog(this, "Metode transaksi tidak dikenali");
            return;
        }
        
        dialogPembayaran.pack();
        dialogPembayaran.setLocationRelativeTo(this);
        dialogPembayaran.setVisible(true);
    }//GEN-LAST:event_transaksiButtonActionPerformed

    private void batalKasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalKasButtonActionPerformed
        dialogPembayaranKas.setVisible(false);
    }//GEN-LAST:event_batalKasButtonActionPerformed

    private void batalKartuDebitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalKartuDebitButtonActionPerformed
        dialogPembayaranKartuDebit.setVisible(false);
    }//GEN-LAST:event_batalKartuDebitButtonActionPerformed

    private void batalQRISButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalQRISButtonActionPerformed
        dialogPembayaranQRIS.setVisible(false);
    }//GEN-LAST:event_batalQRISButtonActionPerformed

    private void konfirmasiKasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiKasButtonActionPerformed
        String nominalString = nominalKasTextField.getText();
        nominalString = nominalString.replace(",", "");
        var nominal = Integer.valueOf(nominalString);
        
        var transaksiKas = new Kas(nominal);
        transaksiKas.setIDPembayaran(getLatestTransactionId());
        transaksiKas.setTotalHarga(totalBelanja);
        transaksiKas.setWaktuPembayaran(LocalDateTime.now());
        
        if (performTransaction()) {
            try {
                Statement stmt = DBConnector.connection.createStatement();
                Statement stmt2 = DBConnector.connection.createStatement();
                Statement stmt3 = DBConnector.connection.createStatement();
                String sql = String.format("INSERT INTO kas (id, dibayar, kembalian) VALUES (%d, %f, %f)", getLatestTransactionId(), transaksiKas.getDibayar(), transaksiKas.getKembalian());
                stmt.executeUpdate(sql);
                String sql2 = "SELECT * FROM transaksi";
                ResultSet rs2 = stmt2.executeQuery(sql2);
                var idTransaksi = 0;
                while (rs2.next()) 
                    {
                    idTransaksi = Math.max(idTransaksi, rs2.getInt("id"));
                    }
                for (int i = 0; i < totalBarang; i++) 
                {
                    var kodeBarang = (String) daftarModel.getValueAt(i, 1);
                    var jumlahBarang = (int) daftarModel.getValueAt(i, 4);
                    int checkItem = Integer.parseInt(kodeBarang)/1000;
                    System.out.println(kodeBarang);
                    if(checkItem == 1)
                        {
                        String sql3 = String.format("INSERT INTO transaksi_barang (id_transaksi, kode_makanan, kode_pln, kode_pulsa, jumlah_barang) VALUES (%d, %s, %s, %s, %d)", idTransaksi, kodeBarang, null,null , jumlahBarang);
                        stmt3.executeUpdate(sql3);
                        }
                    if(checkItem == 2)
                        {
                        String sql3 = String.format("INSERT INTO transaksi_barang (id_transaksi, kode_makanan, kode_pln, kode_pulsa, jumlah_barang) VALUES (%d, %s, %s, %s, %d)", idTransaksi, null, null,kodeBarang , jumlahBarang);
                        stmt3.executeUpdate(sql3);
                        }
                    if(checkItem == 3)
                        {
                        String sql3 = String.format("INSERT INTO transaksi_barang (id_transaksi, kode_makanan, kode_pln, kode_pulsa, jumlah_barang) VALUES (%d, %s, %s, %s, %d)", idTransaksi, null,kodeBarang,null , jumlahBarang);
                        stmt3.executeUpdate(sql3);
                        }
                    }
                JOptionPane.showMessageDialog(this, "Transaksi berhasil!");
            } catch (SQLException ex) {
                Logger.getLogger(POSFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Gagal melakukan transaksi");
        }
        
        dialogPembayaranKas.setVisible(false);
    }//GEN-LAST:event_konfirmasiKasButtonActionPerformed

    private void konfirmasiKartuDebitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiKartuDebitButtonActionPerformed
        var transaksiKartuDebit = new KartuDebit(bankTextField.getText(), nomorKartuTextField.getText());
        transaksiKartuDebit.setIDPembayaran(getLatestTransactionId());
        transaksiKartuDebit.setTotalHarga(totalBelanja);
        transaksiKartuDebit.setWaktuPembayaran(LocalDateTime.now());
        
        if (performTransaction()) {
            try {
                Statement stmt = DBConnector.connection.createStatement();
                Statement stmt2 = DBConnector.connection.createStatement();
                Statement stmt3 = DBConnector.connection.createStatement();
                String sql = String.format("INSERT INTO kartu_debit (id, bank, nomor_kartu) VALUES (%d, \"%s\", \"%s\")", getLatestTransactionId(), transaksiKartuDebit.getBank(), transaksiKartuDebit.getNomorKartu());
                stmt.executeUpdate(sql);
                String sql2 = "SELECT * FROM transaksi";
                ResultSet rs2 = stmt2.executeQuery(sql2);
                var idTransaksi = 0;
                while (rs2.next()) 
                    {
                    idTransaksi = Math.max(idTransaksi, rs2.getInt("id"));
                    }
                for (int i = 0; i < totalBarang; i++) 
                {
                    var kodeBarang = (String) daftarModel.getValueAt(i, 1);
                    var jumlahBarang = (int) daftarModel.getValueAt(i, 4);
                    int checkItem = Integer.parseInt(kodeBarang)/1000;
                    System.out.println(kodeBarang);
                    if(checkItem == 1)
                        {
                        String sql3 = String.format("INSERT INTO transaksi_barang (id_transaksi, kode_makanan, kode_pln, kode_pulsa, jumlah_barang) VALUES (%d, %s, %s, %s, %d)", idTransaksi, kodeBarang, null,null , jumlahBarang);
                        stmt3.executeUpdate(sql3);
                        }
                    if(checkItem == 2)
                        {
                        String sql3 = String.format("INSERT INTO transaksi_barang (id_transaksi, kode_makanan, kode_pln, kode_pulsa, jumlah_barang) VALUES (%d, %s, %s, %s, %d)", idTransaksi, null, null,kodeBarang , jumlahBarang);
                        stmt3.executeUpdate(sql3);
                        }
                    if(checkItem == 3)
                        {
                        String sql3 = String.format("INSERT INTO transaksi_barang (id_transaksi, kode_makanan, kode_pln, kode_pulsa, jumlah_barang) VALUES (%d, %s, %s, %s, %d)", idTransaksi, null,kodeBarang,null , jumlahBarang);
                        stmt3.executeUpdate(sql3);
                        }
                    }
                JOptionPane.showMessageDialog(this, "Transaksi berhasil!");
            } catch (SQLException ex) {
                Logger.getLogger(POSFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Gagal melakukan transaksi");
        }
        
        dialogPembayaranKartuDebit.setVisible(false);
    }//GEN-LAST:event_konfirmasiKartuDebitButtonActionPerformed

    private void konfirmasiQRISButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiQRISButtonActionPerformed
        if (performTransaction() && invoiceQRIS != null) {
            try {
                Statement stmt = DBConnector.connection.createStatement();
                Statement stmt2 = DBConnector.connection.createStatement();
                Statement stmt3 = DBConnector.connection.createStatement();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                String sql = String.format("INSERT INTO qris (id, konten, request_date) VALUES (%d, \"%s\", \"%s\")", getLatestTransactionId(), invoiceQRIS.getKonten(), invoiceQRIS.getRequestDate().format(formatter));
                stmt.executeUpdate(sql);
                String sql2 = "SELECT * FROM transaksi";
                ResultSet rs2 = stmt2.executeQuery(sql2);
                var idTransaksi = 0;
                while (rs2.next()) 
                    {
                    idTransaksi = Math.max(idTransaksi, rs2.getInt("id"));
                    }
                for (int i = 0; i < totalBarang; i++) 
                {
                    var kodeBarang = (String) daftarModel.getValueAt(i, 1);
                    var jumlahBarang = (int) daftarModel.getValueAt(i, 4);
                    int checkItem = Integer.parseInt(kodeBarang)/1000;
                    System.out.println(kodeBarang);
                    if(checkItem == 1)
                        {
                        String sql3 = String.format("INSERT INTO transaksi_barang (id_transaksi, kode_makanan, kode_pln, kode_pulsa, jumlah_barang) VALUES (%d, %s, %s, %s, %d)", idTransaksi, kodeBarang, null,null , jumlahBarang);
                        stmt3.executeUpdate(sql3);
                        }
                    if(checkItem == 2)
                        {
                        String sql3 = String.format("INSERT INTO transaksi_barang (id_transaksi, kode_makanan, kode_pln, kode_pulsa, jumlah_barang) VALUES (%d, %s, %s, %s, %d)", idTransaksi, null, null,kodeBarang , jumlahBarang);
                        stmt3.executeUpdate(sql3);
                        }
                    if(checkItem == 3)
                        {
                        String sql3 = String.format("INSERT INTO transaksi_barang (id_transaksi, kode_makanan, kode_pln, kode_pulsa, jumlah_barang) VALUES (%d, %s, %s, %s, %d)", idTransaksi, null,kodeBarang,null , jumlahBarang);
                        stmt3.executeUpdate(sql3);
                        }
                    }
                JOptionPane.showMessageDialog(this, "Transaksi berhasil!");
            } catch (SQLException ex) {
                Logger.getLogger(POSFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Gagal melakukan transaksi");
        }
        
        dialogPembayaranQRIS.setVisible(false);    }//GEN-LAST:event_konfirmasiQRISButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bankTextField;
    private javax.swing.JButton batalKartuDebitButton;
    private javax.swing.JButton batalKasButton;
    private javax.swing.JButton batalQRISButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxMetodePembayaran;
    private javax.swing.JTable daftarTable;
    private javax.swing.JDialog dialogPembayaranKartuDebit;
    private javax.swing.JDialog dialogPembayaranKas;
    private javax.swing.JDialog dialogPembayaranQRIS;
    private javax.swing.JTextField invoiceIDTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField ketTextField;
    private javax.swing.JTextField kodeTextField;
    private javax.swing.JButton konfirmasiKartuDebitButton;
    private javax.swing.JButton konfirmasiKasButton;
    private javax.swing.JButton konfirmasiQRISButton;
    private javax.swing.JTextField kontenTextField;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nominalKasTextField;
    private javax.swing.JTextField nomorKartuTextField;
    private javax.swing.JTextField requestDateTextField;
    private javax.swing.JToggleButton toggleFood;
    private javax.swing.JToggleButton togglePLN;
    private javax.swing.JToggleButton togglePulsa;
    private javax.swing.JTextField totalBelanjaTextField;
    private javax.swing.JButton transaksiButton;
    // End of variables declaration//GEN-END:variables

    private boolean performTransaction() {
        try {
            Statement stmtInsertTransac = DBConnector.connection.createStatement();
            
            var now = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String sqlInsertTransac = String.format("INSERT INTO transaksi (total_harga, waktu_pembayaran) VALUES (%d, \"%s\")", totalBelanja, now.format(formatter));
            stmtInsertTransac.executeUpdate(sqlInsertTransac);
            
        } catch (Exception e) {
            Logger.getLogger(POSFrame.class.getName()).log(Level.SEVERE, null, e);
            return false;
        }
        
        return true;
    }
    
    private int getLatestTransactionId() {
        var max = 0;

        try {
            Statement stmt = DBConnector.connection.createStatement();

            String sql = "SELECT * FROM transaksi";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                max = Math.max(max, rs.getInt("id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(POSFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        return max;
    }
}
